
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 이대준
 */
public class MainFrame extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    String strSQL = "Select * From games";
    String user_id = "";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        MainFrame.super.getContentPane().setBackground(Color.WHITE);
        try {
            String strData = null;
            DBM.dbOpen();
            getDBData(strSQL);
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }

    }

    //상규 : 위에 MainFrame()생성자에 추가한거 있으면 밑에 생성자에도 추가해줘!
    public MainFrame(String user_id, String user_name) {
        initComponents();
        MainFrame.super.getContentPane().setBackground(Color.WHITE);
        this.user_id = user_id; // <<------------userid
        lblUser.setText(user_name + "님");
        try {
            String strData = null;
            DBM.dbOpen();
            getDBData(strSQL);
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtGameNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBet = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        lblHome = new javax.swing.JLabel();
        lblAway = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnWin = new javax.swing.JButton();
        btnDraw = new javax.swing.JButton();
        btnLose = new javax.swing.JButton();
        txtBetPoint = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUserPoint = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        lblShowPoint = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCharge = new javax.swing.JButton();
        txtChargePoint = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jDialog1.setModal(true);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("고유번호  홈팀  원정팀  결과  경기일");
        jScrollPane1.setViewportView(jTextArea1);

        jDialog1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 370, 240));

        jLabel1.setFont(new java.awt.Font("휴먼엑스포", 0, 12)); // NOI18N
        jLabel1.setText("오늘의 경기");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, -1));

        txtGameNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameNumActionPerformed(evt);
            }
        });
        txtGameNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGameNumKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGameNumKeyTyped(evt);
            }
        });
        jDialog1.getContentPane().add(txtGameNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 40, 30));

        jLabel2.setFont(new java.awt.Font("휴먼엑스포", 0, 12)); // NOI18N
        jLabel2.setText("경기 번호 :");
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 30));

        btnBet.setFont(new java.awt.Font("휴먼엑스포", 0, 14)); // NOI18N
        btnBet.setText("선택");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(btnBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, 30));

        lblHome.setText("jLabel3");

        lblAway.setText("jLabel4");

        jLabel5.setText("VS");

        btnWin.setText("승");
        btnWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinActionPerformed(evt);
            }
        });

        btnDraw.setText("무");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        btnLose.setText("패");
        btnLose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoseActionPerformed(evt);
            }
        });

        txtBetPoint.setText("0");
        txtBetPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetPointActionPerformed(evt);
            }
        });

        jLabel3.setText("배팅 포인트 :");

        jLabel4.setText("보유 포인트 :");

        lblUserPoint.setText("0");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnWin, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(btnDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBetPoint, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnLose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGroup(jDialog2Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(lblAway)))
                    .addComponent(lblUserPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome)
                    .addComponent(lblAway)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblUserPoint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBetPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDialog3.setModal(true);

        lblShowPoint.setText("0");

        jLabel10.setText("보유 포인트");

        btnCharge.setText("충전하기");
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });

        txtChargePoint.setText("0");

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(txtChargePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShowPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblShowPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharge)
                    .addComponent(txtChargePoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Game Schedule");
        jButton2.setIconTextGap(0);
        jButton2.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Betting ");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setMaximumSize(new java.awt.Dimension(150, 150));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 150));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Strategy Analysis");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setText("Sports - Betting");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel8.setText("Just for fun");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/javaimg2.jpg"))); // NOI18N

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Point");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Schedule().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(430, 430);
        jDialog1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtGameNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameNumActionPerformed

    private void txtGameNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGameNumKeyPressed

    }//GEN-LAST:event_txtGameNumKeyPressed

    private void txtGameNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGameNumKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            //TODO 
        }
    }//GEN-LAST:event_txtGameNumKeyTyped

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        strSQL += " WHERE G_No = '" + txtGameNum.getText() + "'";

        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);

            while (DBM.DB_rs.next()) {
                String strHome = DBM.DB_rs.getString("home_team");
                String strAway = DBM.DB_rs.getString("away_team");
                lblHome.setText(strHome);
                lblAway.setText(strAway);

                String strWinOdds = DBM.DB_rs.getString("win_odds");
                String strDrawOdds = DBM.DB_rs.getString("draw_odds");
                String strLoseOdds = DBM.DB_rs.getString("lose_odds");
                btnWin.setText(btnWin.getText() + "\n" + strWinOdds);
                btnDraw.setText(btnDraw.getText() + "\n" + strDrawOdds);
                btnLose.setText(btnLose.getText() + "\n" + strLoseOdds);
            }
            DBM.DB_rs.close();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }

        //보유포인트 lblUserPoint에 띄워주는 로직
        String strSQL2 = "SELECT point FROM user_info where user_id = '" + user_id + "'";
        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL2);

            while (DBM.DB_rs.next()) {
                String point = DBM.DB_rs.getString("point");
                lblUserPoint.setText(point);
            }
            DBM.DB_rs.close();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }

        jDialog2.setSize(382, 300);
        jDialog2.setVisible(true);
    }//GEN-LAST:event_btnBetActionPerformed

    private void txtBetPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetPointActionPerformed

    private void btnWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinActionPerformed
        betting("승");
    }//GEN-LAST:event_btnWinActionPerformed

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
        int ChargePoint = Integer.parseInt(lblShowPoint.getText()) + Integer.parseInt(txtChargePoint.getText());
        String strSQL2 = "Update user_info Set ";
        strSQL2 += "point = '" + ChargePoint + "'";
        strSQL2 += " WHERE user_id ='" + user_id + "'";
        try {
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL2);
            DBM.dbClose();
            JOptionPane.showMessageDialog(null, txtChargePoint.getText() + "원 충전하셨습니다.");
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnChargeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //포인트 충전 화면
        txtChargePoint.setText("0");
        String strSQL2 = "SELECT point FROM user_info where user_id = '" + user_id + "'";
        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL2);

            while (DBM.DB_rs.next()) {
                String point = DBM.DB_rs.getString("point");
                lblShowPoint.setText(point);
            }
            DBM.DB_rs.close();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
        jDialog3.setSize(300, 300);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        betting("무");
    }//GEN-LAST:event_btnDrawActionPerformed

    private void btnLoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoseActionPerformed
        betting("패");
    }//GEN-LAST:event_btnLoseActionPerformed

    public final void getDBData(String strQuery) {
        String strOutput = "고유번호\t홈팀\t원정팀\t경기일정\n";
        jTextArea1.setText(strOutput);
        strQuery += " WHERE DATE_FORMAT(game_date, '%Y-%m-%d') = '" + LocalDate.now().toString() + "'";
        try {
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
            while (DBM.DB_rs.next()) {
                strOutput = "\n";
                strOutput += DBM.DB_rs.getString("G_no") + "\t";
                strOutput += DBM.DB_rs.getString("home_team") + "\t";
                strOutput += DBM.DB_rs.getString("away_team") + "\t";
                strOutput += DBM.DB_rs.getDate("game_date") + "\t";

                jTextArea1.append(strOutput);
            }
            DBM.DB_rs.close();
        } catch (Exception e) {
            System.out.println("SQLException : " + e.getMessage());
        }
    }

    public void betting(String option) {
        //배팅 메소드
        if (Integer.parseInt(txtBetPoint.getText()) > Integer.parseInt(lblUserPoint.getText())) {
            int result = JOptionPane.showConfirmDialog(null, "포인트가 부족합니다. 충전하시겠습니까?", "insufficient balance", JOptionPane.YES_NO_OPTION);
            if (result == 0) {
                String strSQL2 = "SELECT point FROM user_info where user_id = '" + user_id + "'";
                try {
                    DBM.dbOpen();
                    DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL2);

                    while (DBM.DB_rs.next()) {
                        String point = DBM.DB_rs.getString("point");
                        lblShowPoint.setText(point);
                    }
                    DBM.DB_rs.close();
                } catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
                }
                jDialog3.setSize(300, 300);
                jDialog3.setVisible(true);
            }
        } else {
            //B_no + 1 로직
            String strSQL_B_no = "SELECT B_no FROM betting ORDER BY B_no DESC LIMIT 1";
            int B_no = 0;
            try {
                DBM.dbOpen();
                DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL_B_no);

                while (DBM.DB_rs.next()) {
                    B_no = DBM.DB_rs.getInt("B_no") + 1;
                }
                DBM.DB_rs.close();
            } catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
            }

            //디비에 배팅 기록 삽입 로직
            strSQL = "Insert Into betting Values(";
            strSQL += "'" + B_no + "',";
            strSQL += "'" + Integer.parseInt(txtGameNum.getText()) + "',";
            strSQL += "'" + user_id + "',";
            strSQL += "'" + Integer.parseInt(txtBetPoint.getText()) + "',";
            strSQL += "'" + option + "',";
            strSQL += "'" + LocalDate.now() + "',";
            strSQL += "'" + "yet" + "')";
            try {
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                DBM.dbClose();
                JOptionPane.showMessageDialog(null, txtBetPoint.getText() + "원 배팅하셨습니다.");
            } catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
            }

            //디비 유저 포인트 배팅금액만큼 차감 로직
            int change = Integer.parseInt(lblUserPoint.getText()) - Integer.parseInt(txtBetPoint.getText());

            String strSQL2 = "Update user_info Set ";
            strSQL2 += "point = '" + change + "'";
            strSQL2 += " WHERE user_id ='" + user_id + "'";
            try {
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL2);
                DBM.dbClose();
            } catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
                frame.setBackground(Color.white);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBet;
    private javax.swing.JButton btnCharge;
    private javax.swing.JButton btnDraw;
    private javax.swing.JButton btnLose;
    private javax.swing.JButton btnWin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAway;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblShowPoint;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserPoint;
    private javax.swing.JTextField txtBetPoint;
    private javax.swing.JTextField txtChargePoint;
    private javax.swing.JTextField txtGameNum;
    // End of variables declaration//GEN-END:variables
}
