

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

;



/**
 *
 * @author 이대준
 */
public class SignUp extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    boolean id_is_overlap = true;
    FileFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
    
    /**
     * Creates new form MainFrame
     */
    public SignUp() {
        initComponents();
        SignUp.super.getContentPane().setBackground(Color.WHITE);
        lblEnable.setVisible(false);
        lblImagename.setVisible(false);
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(filter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        lblPws = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        txtPwcheck = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnOverlap = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        lblEnable = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblImagepath = new javax.swing.JLabel();
        btnX = new javax.swing.JButton();
        lblImagename = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("회원가입");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setSize(new java.awt.Dimension(230, 23));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("회원 가입");

        lblPw.setText("비밀번호");

        lblPws.setText("비밀번호 확인");

        lblName.setText("성 명");

        lblId.setText("아이디");

        txtId.setMinimumSize(new java.awt.Dimension(138, 23));
        txtId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtIdInputMethodTextChanged(evt);
            }
        });
        txtId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtIdPropertyChange(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });

        btnOverlap.setText("중복 확인");
        btnOverlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverlapActionPerformed(evt);
            }
        });

        btnSignup.setText("회원 가입");
        btnSignup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        lblEnable.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        lblEnable.setForeground(new java.awt.Color(255, 0, 51));
        lblEnable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnable.setText("이미 존재하는 아이디입니다;;");

        lblName1.setText("프로필 사진(jpeg)");

        btnImage.setText("사진불러오기");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        lblImagepath.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblImagepath.setMaximumSize(new java.awt.Dimension(226, 0));

        btnX.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btnX.setForeground(new java.awt.Color(255, 0, 51));
        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        lblImagename.setMaximumSize(new java.awt.Dimension(226, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagename, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPw)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPws)
                            .addComponent(lblName)
                            .addComponent(lblName1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEnable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPw, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtPwcheck, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtName))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOverlap))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagepath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(btnOverlap))
                .addGap(2, 2, 2)
                .addComponent(lblEnable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPw)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPws)
                    .addComponent(txtPwcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImage)
                    .addComponent(lblName1)
                    .addComponent(btnX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagepath, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagename, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOverlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverlapActionPerformed
        id_is_overlap = true;
        String checkingid = txtId.getText().trim();
        String strSQL = "Select * From user Where user_id = '"+checkingid+"';";
        
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            if(DBM.DB_rs.next()){
                lblEnable.setForeground(Color.red);
                lblEnable.setText("이미 존재하는 아이디입니다;;");
            }else if(checkingid.isEmpty()){
                lblEnable.setForeground(Color.red);
                lblEnable.setText("아이디를 입력해주십시오...");
            }else{
                lblEnable.setForeground(Color.BLUE);
                lblEnable.setText("사용가능한 아이디 입니다!");
                id_is_overlap = false;
            }
            lblEnable.setVisible(true);
        }catch(Exception e){
            System.out.println("Exception : "+e);
        }
    }//GEN-LAST:event_btnOverlapActionPerformed
    
    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String user_id = txtId.getText().trim();
        String user_pw = txtPw.getText().trim();
        String user_pwcheck = txtPwcheck.getText().trim();
        String user_name = txtName.getText().trim();
        String user_profile;
        
        String realpath = lblImagepath.getText();
        String filename = lblImagename.getText();
        String relativepath = "src/org/me/myimageapp/profileImage/";

        File file;
        File newFile;
        
        file = new File(realpath);
        newFile = new File(relativepath+filename);
        
        String strSQL_user = "Insert Into user Values(";
        strSQL_user += "'"+user_id+"',";
        strSQL_user += "'"+user_pw+"');";
        String strSQL_ui;
        
        if(realpath.isEmpty()){
            strSQL_ui = "Insert Into user_info(user_id, user_name) Values( ";
            strSQL_ui += "'"+user_id+"',";
            strSQL_ui += "'"+user_name+"');";
        }else{
            try {
                Files.copy(file.toPath(), newFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException e) {
                System.out.println("IOException : "+e);
            }
            user_profile = relativepath + filename;
            strSQL_ui = "Insert Into user_info(user_id, user_name, user_profile) Values( ";
            strSQL_ui += "'"+user_id+"',";
            strSQL_ui += "'"+user_name+"',";
            strSQL_ui += "'"+user_profile+"');";
        }
        
//        
//        String strSQL = "Insert Into user Values(";
//        strSQL += "'"+user_id+"',";
//        strSQL += "'"+user_pw+"',";
//        strSQL += "'"+user_name+"',";
//        strSQL += "'"+user_profile+"',";
//        strSQL += "sysdate());";
//        
        
         
        if(id_is_overlap){
            JOptionPane.showMessageDialog(null, "중복확인을 해주세요.");
            return;
        }
        if(!user_pw.trim().equals(user_pwcheck)){
            JOptionPane.showMessageDialog(null, "비밀번호가 맞지 않습니다.");
            return;
        }
        if(user_pw.isEmpty() || user_pwcheck.isEmpty() || user_name.isEmpty()){
            JOptionPane.showMessageDialog(null, "빈칸을 입력해주세요.");
            return;
        }
        
        try {
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL_user);
            DBM.DB_stmt.execute(strSQL_ui);
            JOptionPane.showMessageDialog(null, "회원가입이 완료되었습니다.");
            DBM.dbClose();
            super.dispose();
        } catch (Exception e) {
            System.out.println("SQLException : "+e.getMessage());
        }
        //JOptionPane.showMessageDialog(null, "회원가입이 완료되었습니다.");
    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtIdInputMethodTextChanged

    }//GEN-LAST:event_txtIdInputMethodTextChanged

    private void txtIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtIdPropertyChange

    }//GEN-LAST:event_txtIdPropertyChange

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        lblEnable.setVisible(false);
        id_is_overlap = true;
    }//GEN-LAST:event_txtIdKeyPressed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        jFileChooser1.showOpenDialog(null);
        String realPath;
        String filename;
        
        try {
            realPath = jFileChooser1.getSelectedFile().getAbsolutePath();
            filename = jFileChooser1.getSelectedFile().getName();
        } catch (Exception e) {
            System.out.println("Exeption : "+e);
            return;
        }
        lblImagepath.setText(realPath);
        lblImagename.setText(filename);
        
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        lblImagepath.setText("");
        lblImagename.setText("");
    }//GEN-LAST:event_btnXActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainFrame().setVisible(true);
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnOverlap;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton btnX;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnable;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagename;
    private javax.swing.JLabel lblImagepath;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPws;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtPwcheck;
    // End of variables declaration//GEN-END:variables
}
